# Generated by Django 4.2 on 2023-12-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
